name: Stephen Paul Krueger
favicon: null
layout_spectrum: 0.49309
typography_spectrum: 0.14625
title: Stephen Paul Krueger
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bcc5d4'
    - '#050608'
    - '#faf8fb'
    - '#ad9676'
    - '#3e4346'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
