name: Stephen Paul Krueger
favicon: null
layout_spectrum: 0.24935
typography_spectrum: 0.14625
title: Stephen Paul Krueger
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
